version: "3.8"

# https://github.com/lensesio/fast-data-dev

# Please increase your docker vm memory to 4 GB, at least!
# Run the kafka-cluster service, and wait the cluster boot up
# Access the Lenses.io UI at http://localhost:3030/

# create a topic:      kafka-topics --bootstrap-server 127.0.0.1:9092 --topic <topic_name> --create
# describe your topic: kafka-topics --bootstrap-server 127.0.0.1:9092 --topic <topic_name> --describe


services:
  postgres:
    image: postgres:13.4
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rust -d rust-sample" ]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: rust
      POSTGRES_PASSWORD: fresh4you
      POSTGRES_DB: rust-sample
